/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jframe;
import BD.ConexionBD;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;
import java.time.LocalDate;

/**
 *
 * @author Hensser
 */
public class Nomina extends javax.swing.JFrame {

    /**
     * Creates new form Nomina
     */
    public Nomina() {
        initComponents();
        this.setLocationRelativeTo(null);
        getContentPane().setBackground(new Color(255, 250, 245));
        aplicarColores();
        tablaNominas.getSelectionModel().addListSelectionListener(event -> {
        if (!event.getValueIsAdjusting() && tablaNominas.getSelectedRow() != -1) {
        int fila = tablaNominas.getSelectedRow();
        txtIdNomina.setText(tablaNominas.getValueAt(fila, 0).toString());
        txtIdEmpleado.setText(tablaNominas.getValueAt(fila, 1).toString());
        txtIdDepartamento.setText(tablaNominas.getValueAt(fila, 2).toString());
        txtMes.setText(tablaNominas.getValueAt(fila, 3).toString());
        txtAnio.setText(tablaNominas.getValueAt(fila, 4).toString());
        txtSalarioBase.setText(tablaNominas.getValueAt(fila, 5).toString());
        txtHorasExtras.setText(tablaNominas.getValueAt(fila, 6).toString());
        txtBonificacion.setText(tablaNominas.getValueAt(fila, 7).toString());
        txtDescuentos.setText(tablaNominas.getValueAt(fila, 8).toString());
        txtTotalPagar.setText(tablaNominas.getValueAt(fila, 9).toString());
        txtFechaPago.setText(tablaNominas.getValueAt(fila, 10).toString());
    }
});
        
    }
    private void aplicarColores()
    {
        Color rojo = new Color(220, 50, 50);
        JButton[] botones = {btnAgregar, btnEditar, btnMostrar, btnEliminar, btnLimpiar, btnVolver};
        for (JButton b : botones) {
            b.setBackground(rojo);
            b.setForeground(Color.WHITE);
            b.setFocusPainted(false);
            b.setBorderPainted(false);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jDialog1 = new javax.swing.JDialog();
        jOptionPane1 = new javax.swing.JOptionPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtIdNomina = new javax.swing.JTextField();
        txtIdEmpleado = new javax.swing.JTextField();
        txtMes = new javax.swing.JTextField();
        txtAnio = new javax.swing.JTextField();
        txtSalarioBase = new javax.swing.JTextField();
        txtHorasExtras = new javax.swing.JTextField();
        txtBonificacion = new javax.swing.JTextField();
        txtDescuentos = new javax.swing.JTextField();
        txtTotalPagar = new javax.swing.JTextField();
        txtFechaPago = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaNominas = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtIdDepartamento = new javax.swing.JTextField();

        jLabel9.setText("jLabel9");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion de Nomina");

        jLabel1.setText("ID Nomina");

        jLabel2.setText("ID Empleado");

        jLabel3.setText("Mes");

        jLabel4.setText("Año");

        jLabel5.setText("Salario Base");

        jLabel6.setText("Horas extras");

        jLabel7.setText("Bonificacion");

        jLabel8.setText("Descuentos");

        jLabel10.setText("Total a Pagar");

        jLabel11.setText("Fecha de Pago");

        txtIdNomina.setEnabled(false);

        tablaNominas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Nomina", "ID Empleado", "ID Depto", "Mes", "Año", "Salario Base", "Horas Extras", "Bonificacion", "Descuentos", "Total a Pagar", "Fecha de Pago"
            }
        ));
        jScrollPane1.setViewportView(tablaNominas);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jLabel12.setText("ID Depto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtIdEmpleado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(txtIdNomina, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 924, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtTotalPagar, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                        .addComponent(txtDescuentos)
                                        .addComponent(txtBonificacion)
                                        .addComponent(txtHorasExtras)
                                        .addComponent(txtSalarioBase)
                                        .addComponent(txtAnio)
                                        .addComponent(txtMes)
                                        .addComponent(txtFechaPago, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                        .addComponent(txtIdDepartamento))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(btnAgregar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btnMostrar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar)
                        .addGap(18, 18, 18)
                        .addComponent(btnVolver)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdNomina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtIdDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtSalarioBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtHorasExtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtBonificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtDescuentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(txtFechaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnEditar)
                    .addComponent(btnMostrar)
                    .addComponent(btnEliminar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnVolver))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
         if (txtIdEmpleado.getText().isEmpty() || txtMes.getText().isEmpty() || 
            txtAnio.getText().isEmpty() || txtSalarioBase.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Completa todos los campos obligatorios.");
            return;
        }

        try (Connection con = ConexionBD.conectar()) {
            double salario = Double.parseDouble(txtSalarioBase.getText());
            double extras = Double.parseDouble(txtHorasExtras.getText());
            double bonif = Double.parseDouble(txtBonificacion.getText());
            double desc = Double.parseDouble(txtDescuentos.getText());
            double total = salario + extras + bonif - desc;
            txtTotalPagar.setText(String.valueOf(total));

            String fechaPago = txtFechaPago.getText().isEmpty() ? LocalDate.now().toString() : txtFechaPago.getText();

            String sql = "INSERT INTO nominas (id_empleado, id_departamento, mes, anio, salario_base, horas_extras, bonificacion, descuentos, total_pagar, pagada, fecha_pago) "
           + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 1, ?)";

            PreparedStatement ps = con.prepareStatement(sql);
            ps.setInt(1, Integer.parseInt(txtIdEmpleado.getText()));
            ps.setInt(2, Integer.parseInt(txtIdDepartamento.getText())); 
            ps.setString(3, txtMes.getText());
            ps.setString(4, txtAnio.getText());
            ps.setDouble(5, salario);
            ps.setDouble(6, extras);
            ps.setDouble(7, bonif);
            ps.setDouble(8, desc);
            ps.setDouble(9, total);
            ps.setString(10, fechaPago);
            ps.executeUpdate();

            JOptionPane.showMessageDialog(this, "Nómina agregada correctamente.");
            mostrarNominas();
            limpiarCampos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al agregar nómina: " + e.getMessage());
        }
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        int fila = tablaNominas.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona una nómina para editar.");
            return;
        }

        int id = Integer.parseInt(tablaNominas.getValueAt(fila, 0).toString());

        try (Connection con = ConexionBD.conectar()) {
            double salario = Double.parseDouble(txtSalarioBase.getText());
            double extras = Double.parseDouble(txtHorasExtras.getText());
            double bonif = Double.parseDouble(txtBonificacion.getText());
            double desc = Double.parseDouble(txtDescuentos.getText());
            double total = salario + extras + bonif - desc;
            txtTotalPagar.setText(String.valueOf(total));

            String sql = "UPDATE nominas SET id_empleado=?, id_departamento=?, mes=?, anio=?, salario_base=?, horas_extras=?, bonificacion=?, descuentos=?, total_pagar=?, fecha_pago=? WHERE id_nomina=?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setInt(1, Integer.parseInt(txtIdEmpleado.getText()));
            ps.setInt(2, Integer.parseInt(txtIdDepartamento.getText()));
            ps.setString(3, txtMes.getText());
            ps.setString(4, txtAnio.getText());
            ps.setDouble(5, salario);
            ps.setDouble(6, extras);
            ps.setDouble(7, bonif);
            ps.setDouble(8, desc);
            ps.setDouble(9, total);
            ps.setString(10, txtFechaPago.getText());
            ps.setInt(11, id);
            ps.executeUpdate();

            JOptionPane.showMessageDialog(this, "Nómina actualizada correctamente.");
            mostrarNominas();
            limpiarCampos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al editar nómina: " + e.getMessage());
        }
        
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        mostrarNominas();
        limpiarCampos();
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int fila = tablaNominas.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona una nómina para eliminar.");
            return;
        }

        int id = Integer.parseInt(tablaNominas.getValueAt(fila, 0).toString());

        try (Connection con = ConexionBD.conectar()) {
            String sql = "DELETE FROM nominas WHERE id_nomina=?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setInt(1, id);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Nómina eliminada correctamente.");
            mostrarNominas();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:                                         
        limpiarCampos();
        limpiarTabla();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
         this.dispose();
        new MenuPrincipal().setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
  private void mostrarNominas() {
    try (Connection con = ConexionBD.conectar();
         Statement st = con.createStatement();
         ResultSet rs = st.executeQuery(
             "SELECT id_nomina, id_empleado, id_departamento, mes, anio, salario_base, horas_extras, bonificacion, descuentos, total_pagar, fecha_pago FROM nominas"
         )) {

        DefaultTableModel modelo = new DefaultTableModel(
            new Object[]{"ID Nómina", "ID Empleado", "ID Departamento", "Mes", "Año", 
                         "Salario Base", "Horas Extras", "Bonificación", "Descuentos", 
                         "Total a Pagar", "Fecha de Pago"}, 0
        );

        while (rs.next()) {
            modelo.addRow(new Object[]{
                rs.getInt("id_nomina"),
                rs.getInt("id_empleado"),
                rs.getInt("id_departamento"),
                rs.getString("mes"),
                rs.getString("anio"),
                rs.getDouble("salario_base"),
                rs.getDouble("horas_extras"),
                rs.getDouble("bonificacion"),
                rs.getDouble("descuentos"),
                rs.getDouble("total_pagar"),
                rs.getString("fecha_pago")
            });
        }

        tablaNominas.setModel(modelo);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al mostrar nóminas: " + e.getMessage());
    }
}

    private void limpiarCampos() {
        txtIdNomina.setText("");
        txtIdEmpleado.setText("");
        txtIdDepartamento.setText("");
        txtMes.setText("");
        txtAnio.setText("");
        txtSalarioBase.setText("");
        txtHorasExtras.setText("");
        txtBonificacion.setText("");
        txtDescuentos.setText("");
        txtTotalPagar.setText("");
        txtFechaPago.setText("");
    }
     private void limpiarTabla() {
    DefaultTableModel modelo = (DefaultTableModel) tablaNominas.getModel();
    modelo.setRowCount(0); // 
     }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nomina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaNominas;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtBonificacion;
    private javax.swing.JTextField txtDescuentos;
    private javax.swing.JTextField txtFechaPago;
    private javax.swing.JTextField txtHorasExtras;
    private javax.swing.JTextField txtIdDepartamento;
    private javax.swing.JTextField txtIdEmpleado;
    private javax.swing.JTextField txtIdNomina;
    private javax.swing.JTextField txtMes;
    private javax.swing.JTextField txtSalarioBase;
    private javax.swing.JTextField txtTotalPagar;
    // End of variables declaration//GEN-END:variables
}
